// what is javascript.
/* Javasript is a server-side and client side scripting 
and object oriented  language used create web application 
and desktop application */
// also used to create android app using js library.

// Features.
// 1.Server side(backed) and client side(frontend) supportive.
// 2.Easily integrated with HTML-CSS
// 3.Dynamically typed language.
// 4.Event-Driven programming.
// 5.synchronous(sync) and asynchnonous(async)
// 6.By default single threaded and also used as multithreaded.
// 7.Top Libraries : Reactjs, vuejs,angularjs,electronjs.

// Type of applying javascript:
// 1.Internal JS
// 2.External JS


//var name=prompt("Enter your name :")
      // document.write(name)
    //    document.write("<hr>")

    //    document.write("How are you")

       const str = ['rinku','aman','sandeep','shashi','ram']
       console.log(str.splice(2,0,'shashi'))
       console.log(str.slice(1,4))
